### ISSUE TITLE
Don't understand the purpose of this extension with slack-redir

### ISSUE THREAD

**Issue by e-t-l** [Rob--W/dont-slack-redir#1]
> Extension to prevent Slack from replacing external links with "slack-redir.net", and prevent referrer leakage, so that your Slack URL does not end up in the access logs of the linked website

From Twitter:
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">👋🏻 slack-redir is an optional setting to keep your workspace URL from showing up in external sites&#39; referrer logs. Your workspace Admins and Owners can turn it off if they&#39;d like: <a href="https://t.co/Vmb31yxEYk">https://t.co/Vmb31yxEYk</a></p>&mdash; Slack (@SlackHQ) <a href="https://twitter.com/SlackHQ/status/1069996998592528385?ref_src=twsrc%5Etfw">December 4, 2018</a></blockquote> 

It sounds like slack-redir exists _in order_ to prevent referrer leakage. Wouldn't disabling slack-redir therefore _create_ leakage?

**Comment by Rob--W** [comment]
Modern browsers have a feature called Referrer Policy. That can be used to clear the referrer without turning the link into garbage.

This extension overrides the referrer policy on the link when it rewrites the URL to something readable: https://github.com/Rob--W/dont-slack-redir/blob/e5646287671cb202193d51c03b770c3b40eb3bd2/cleanlink.js#L38

Note that I reviewed existing extensions before publishing mine, and none of them accounted for this referrer leakage, as mentioned in the extension description at https://github.com/Rob--W/dont-slack-redir/blob/master/README.md

**Comment by e-t-l** [comment]
Right, I saw that. But isn't the purpose of slack-redir already to prevent referrer leakage revealing the user's slack workspace url? This seems, at best, redundant. Unless the your goal is to hide that it's coming slack at all (in which case, why?)

**Comment by Rob--W** [comment]
The goal of this extension is to ensure that the URL is readable. Without it, hovering or clicking on a link will show slack-redir instead of the actual destination. I have another extension that offers similar functionality on Google; for another explanation + screenshot, see https://github.com/Rob--W/dont-track-me-google.

The original stated purpose of Slack's slack-redir setting is to clear the referrer. That desired functional behavior is implemented in a more user-friendly way by this extension.

**Comment by e-t-l** [comment]
I understand now, thank you.
